// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heuurodakbjehwugjzqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhldXVyb2Rha2JqZWh3dWdqenFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDM2ODMsImV4cCI6MjA2NTQ3OTY4M30.4Fl3zdPCDl9zCS7UqmJujdURvS6KVQM3auJgXQ-Dr8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);